### ISSUE TITLE
RSS feed for book posts

### ISSUE THREAD

**Issue by ohjay** [sagangwee/sagangwee.github.io#2]
Suggestion: add the `books` collection to your current RSS feed (/to a separate feed, whatever works). I think you can follow a process similar to the one described [here](http://stories.upthebuzzard.com/jekyll_notes/2017-02-19-rss-feed-for-a-jekyll-collection.html).

Would like to read your notes as they're released!

**Comment by sagangwee** [comment]
Sure. I'll try it. Thanks!

**Comment by sagangwee** [comment]
Actually, I'm not sure exactly what you want it to look like lol. I've never used RSS feeds myself.

**Comment by ohjay** [comment]
Thanks, I've got it now! Incidentally, it might be good to include the posts' contents as well.

<img width="703" alt="books_rss" src="https://cloud.githubusercontent.com/assets/8358648/26759702/c386487c-48ba-11e7-9a20-3d04ad1d128d.png">

**Comment by ohjay** [comment]
I think you just need to insert the line `<content type="html">{{ post.content | xml_escape }}</content>` into `collection_feed.xml` – maybe use `atom.xml` as an example.

**Comment by sagangwee** [comment]
Isn't there usually some button you click to subscribe?

**Comment by ohjay** [comment]
Yep! Do you maybe not have an aggregator?

**Comment by sagangwee** [comment]
Nope. Don't think so. Oh well, at least you got your link.
